# Constants
from pygame.examples.grid import TILE_SIZE

TILE_SIZE = 16
INITIAL_SCREEN_WIDTH = 800
INITIAL_SCREEN_HEIGHT = 600
FPS = 60  # Target frame rate
TPS = 60
FRICTION_COEFFICIENT = 40
INITIAL_GROUND_LEVEL = INITIAL_SCREEN_HEIGHT * 0.65
FOLLOW_POINT_RETURN_INTERVAL = 2 * FPS
DEBUG_FONT_SIZE = 18
UI_GAP = 5
GRAVITY = 29.8*TILE_SIZE
